# #####################################################################
# Automatically generated by qmake (2.01a) Fri Oct 21 08:15:16 2011
# #####################################################################
TEMPLATE = app
TARGET = QtTemplate
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit

# Input
SOURCES += main.cpp \ 
    mainwindow.cpp
    

# install
target.path = .
INSTALLS += target
FORMS = \ 
    mainwindow.ui

HEADERS += \
    mainwindow.h \
    ui_mainwindow.h
    
